name: canseer_dev
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8.12
  - numpy=1.23.2
  - conda=23.11.0
  - matplotlib=3.5.3
  - plotly=5.18.0
  - jupyterlab=3.4.6
  - seaborn=0.13.0
  - geopandas=0.13.2
  - openpyxl=3.1.2
